name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cs:
    name: CS checker
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
      - name: Check cs
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --diff --dry-run --using-cache=no .
  tests:
    name: Unit tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
      - name: Run tests
        run: vendor/bin/phpunit tests